When building chrome with GYP_DEFINES=use_ozone=1 ozone_platform_wayland=1 use_wayland_egl=1 use_gtk=0 use_glib=1 use_egl=1, the following build error occurred.
n file included from ../../ui/ozone/platform/wayland/wayland_egl_surface.cc:9:
../../third_party/khronos/EGL/egl.h:39:10: fatal error: 'EGL/eglplatform.h' file not found
#include <EGL/eglplatform.h>
         ^
1 error generated.

We need to include khronos in wayland.gypi and wayland/BUILD.gn to
fix this problem.

TEST=build  chrome with GYP_DEFINES=use_ozone=1 ozone_platform_wayland=1
use_wayland_egl=1 use_gtk=0 use_glib=1 use_egl=1
BUG=none

Review-Url: https://codereview.chromium.org/1943593002
Cr-Commit-Position: refs/heads/master@{#391668}