Revert of Use a single views::MenuConfig instance for each platform (patchset #7 id:140001 of https://codereview.chromium.org/1477253002/ )
Reason for revert:
This broke compilation on https://build.chromium.org/p/chromium.android/builders/Android%20Aura%20Builder%20%28dbg%29/builds/2497/steps/compile/logs/stdio (the patch landed in an earlier build, but was masked by another compile failure :-|):

../../ui/views/controls/menu/menu_config.cc:45: error: undefined reference to 'views::MenuConfig::Init()'

Original issue's description:
> Use a single views::MenuConfig instance for each platform
>
> Most noticeably, always use the GTK-style menu layout on Desktop Linux.
>
> Previously, the MenuConfig used by a particular MenuItemView could be
> affected by that View's Widget's GetNativeTheme().
>
> This once allowed a menu to decide whether to use a ChromeOS-style menu
> or a native Desktop-style menu config on the same platform. But that's
> no longer needed, and makes trouble with the "Classic Theme" in Desktop
> Linux. (e.g. because menus are not always in a Widget when they are
> configured, so the native theme is hard to determine.)
>
> Using a single instance simplifies things and fixes a regression where
> the Ash-style was being used on Desktop Linux, resulting in menus
> without a border and unexpectedly large item padding. Regression due to
> the combination of r344651, r345479, and r360168.
>
> Note this means --open-ash on Desktop Linux, and Metro mode on Windows,
> will use non-Ash menus. See screenshots at http://crbug.com/544550#c13
>
> BUG=415953, 544550
>
> Committed: https://crrev.com/5d23f8c18f1d9fbf1655ece40b31d59dea443c60
> Cr-Commit-Position: refs/heads/master@{#363924}

TBR=sky@chromium.org,estade@chromium.org,tapted@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=415953, 544550

Review URL: https://codereview.chromium.org/1514693006

Cr-Commit-Position: refs/heads/master@{#364371}