Revert of Only call gles2::Terminate when all Display objects are deleted (patchset #3 id:40001 of  )
Reason for revert:
Does not compile on win
c:\b\build\slave\win\build\src\gpu\command_buffer\tests\egl_test.cc(87) : error C2059: syntax error : '('
c:\b\build\slave\win\build\src\gpu\command_buffer\tests\egl_test.cc(90) : error C2061: syntax error : identifier 'glEnableProc'
c:\b\build\slave\win\build\src\gpu\command_buffer\tests\egl_test.cc(91) : error C3536: 'GLES2Enable': cannot be used before it is initialized
c:\b\build\slave\win\build\src\gpu\command_buffer\tests\egl_test.cc(91) : error C2064: term does not evaluate to a function taking 1 arguments

https://build.chromium.org/p/chromium/builders/Win/builds/40478/steps/compile/logs/stdio

Original issue's description:
> Only call gles2::Terminate when all Display objects are deleted
>
> Implementation in command buffer EGL calls gles2::Terminate and gles2::Initialize incorrectly. If there are multiple Display objects each will call Initialize and Terminate and creates and frees the TLS allocated context key twice. It should only be created once and freed once all the Displays are deleted.
>
> BUG=skia:2992
>
> Committed: https://crrev.com/c22b484a0aaabbfbce221b419da48bca080e7826
> Cr-Commit-Position: refs/heads/master@{#376439}

TBR=piman@chromium.org,kkinnunen@nvidia.com,svaisanen@nvidia.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=skia:2992

Review URL: https://codereview.chromium.org/1714023002

Cr-Commit-Position: refs/heads/master@{#376443}