Revert of mus: Add views_mus_interactive_ui_tests target (patchset #9 id:150001 of https://codereview.chromium.org/1972363002/ )
Reason for revert:
Broke Chromium Win on Win x64 Builder (dbg)

[3415/4254] CXX obj/ui/views/mus/views_mus_interactive_ui_tests/widget_interactive_uitest.obj
FAILED: obj/ui/views/mus/views_mus_interactive_ui_tests/widget_interactive_uitest.obj
ninja -t msvc -e environment.x64 -- C:\b\build\slave\cache\cipd\goma/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/ui/views/mus/views_mus_interactive_ui_tests/widget_interactive_uitest.obj.rsp /c ../../ui/views/widget/widget_interactive_uitest.cc /Foobj/ui/views/mus/views_mus_interactive_ui_tests/widget_interactive_uitest.obj /Fd"obj/ui/views/mus/views_mus_interactive_ui_tests_cc.pdb"
c:\b\build\slave\win_x64_builder__dbg_\build\src\ui\views\widget\widget_interactive_uitest.cc(658): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_x64_builder__dbg_\build\src\ui\views\widget\widget_interactive_uitest.cc(658): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

Original issue's description:
> mus: Add views_mus_interactive_ui_tests target
>
> * Run widget_interactive_uitests.cc in the new target.
> * Added a shared "test_support" target in ui/views/mus.
> * Pull ViewsMusTestSuite into its own file so I can share it.
> * Also make ViewsTestBase::IsMus static so I can call it before the
>   PlatformTestHelper is initialized.
> * Disable a bunch of tests that fail on mus (I filed bugs for them).
>
> BUG=602036
> TEST=views_interactive_ui_tests on mus, interactive_ui_tests elsewhere
>
> Committed: https://crrev.com/94b68793a258e9261d1dc39cc5fdd2de673ec888
> Cr-Commit-Position: refs/heads/master@{#394026}

TBR=sky@chromium.org,dpranke@chromium.org,sadrul@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=602036

Review-Url: https://codereview.chromium.org/1980283002
Cr-Commit-Position: refs/heads/master@{#394033}