Revert of Show snackbar with "undo" when deleting most visited item. (patchset #3 id:40001 of https://codereview.chromium.org/1587193009/ )
Reason for revert:
Breaks Android bots:

util.build_utils.CalledProcessError: Command failed: ( cd /b/build/slave/Android_Builder__dbg_/build/src/chrome; javac -g -encoding UTF-8 -classpath /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//platforms/android-23/android.jar:../out/Debug/lib.java/protobuf_nano_javalib.jar:../out/Debug/lib.java/document_tab_model_info_proto_java.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/android/support/multidex/library/libs/android-support-multidex.jar:../out/Debug/lib.java/jsr_305_javalib.jar:../out/Debug/lib.java/base_java.jar:../out/Debug/lib.java/bookmarks_java.jar:../out/Debug/lib.java/mojo_public_java.jar:../out/Debug/lib.java/mojo_bindings_java.jar:../out/Debug/lib.java/device_battery_java.jar:../out/Debug/lib.java/device_bluetooth_java.jar:../out/Debug/lib.java/device_usb_java.jar:../out/Debug/lib.java/device_vibration_java.jar:../out/Debug/lib.java/media_java.jar:../out/Debug/lib.java/mojo_system_java.jar:../out/Debug/lib.java/net_java.jar:../out/Debug/lib.java/ui_java.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/android/support/v13/android-support-v13.jar:../out/Debug/lib.java/blink_headers_java.jar:../out/Debug/lib.java/ui_accessibility_java.jar:../out/Debug/lib.java/midi_java.jar:../third_party/cardboard-java/src/CardboardSample/libs/cardboard.jar:../out/Debug/lib.java/content_java.jar:../out/Debug/lib.java/dom_distiller_java.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/android/support/v7/mediarouter/libs/android-support-v7-mediarouter.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/android/support/v7/appcompat/libs/android-support-v7-appcompat.jar:../out/Debug/lib.java/android_support_v7_appcompat_javalib.jar:../out/Debug/lib.java/android_support_v7_mediarouter_javalib.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//platforms/android-23/optional/org.apache.http.legacy.jar:../out/Debug/lib.java/google_play_services_default_javalib_no_res.pre.jar:../out/Debug/lib.java/google_play_services_default_javalib.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/google/gcm/gcm-client/dist/gcm.jar:../out/Debug/lib.java/cacheinvalidation_proto_java.jar:../out/Debug/lib.java/cacheinvalidation_javalib.jar:../out/Debug/lib.java/sync_java.jar:../out/Debug/lib.java/gcm_driver_java.jar:../out/Debug/lib.java/invalidation_proto_java.jar:../out/Debug/lib.java/invalidation_java.jar:../out/Debug/lib.java/navigation_interception_java.jar:../out/Debug/lib.java/precache_java.jar:../out/Debug/lib.java/safe_json_java.jar:../out/Debug/lib.java/service_tab_launcher_java.jar:../out/Debug/lib.java/signin_core_browser_java.jar:../out/Debug/lib.java/variations_java.jar:../out/Debug/lib.java/web_contents_delegate_android_java.jar:../out/Debug/lib.java/web_restriction_java.jar:../out/Debug/lib.java/printing_java.jar:../out/Debug/lib.java/android_data_chart_java.jar:../out/Debug/lib.java/android_media_java.jar:../out/Debug/lib.java/android_swipe_refresh_java.jar:/b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//extras/android/support/v7/recyclerview/libs/android-support-v7-recyclerview.jar:../out/Debug/lib.java/android_support_v7_recyclerview_javalib.jar:../out/Debug/lib.java/gif_player_java.jar:../out/Debug/lib.java/policy_java.jar -sourcepath '' -bootclasspath /b/build/slave/Android_Builder__dbg_/build/src/third_party/android_tools/sdk//platforms/android-23/android.jar -source 1.7 -target 1.7 -Xlint:unchecked -Xlint:deprecation -d /tmp/tmp7ijO7r/classes ../chrome/android/java/src/com/google/android/apps/chrome/appwidget/bookmarks/BookmarkThumbnailWidgetProvider.java ../chrome/android/java/src/org/chromium/chrome/browser/IntentHandler.java ../chrome/android/java/src/org/chromium/chrome/browser/ShortcutHelper.java ../chrome/android/java/src/org/chromium/chrome/browser/partnercustomizations/HomepageManager.java
...
../chrome/android/java/src/org/chromium/chrome/browser/ntp/NewTabPage.java:600: error: method does not override or implement a method from a supertype
                @Override
                ^
1 error

Original issue's description:
> Show snackbar with "undo" when deleting most visited item.
>
> When the user removes a most visited item from the NTP (via long press >
> Remove), we now show a snackbar that says:
>
>   [ Item removed    | Undo ]
>
> If the user clicks the Undo button, the most visited item is added back.
> Navigating away from the NTP will cause the snackbar to be hidden
> immediately.
>
> BUG=368333
>
> Committed: https://crrev.com/5445601850e5f71ba2161512b09f86aee0fc2273
> Cr-Commit-Position: refs/heads/master@{#370317}

TBR=tedchoc@chromium.org,newt@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=368333

Review URL: https://codereview.chromium.org/1606013004

Cr-Commit-Position: refs/heads/master@{#370324}