clang/win: Fix build after https://codereview.chromium.org/1496093002
clang was complaining that it wasn't clear if the if (owner = foo) expression
was an assignment (in which case one usually writes if ((owner = foo))) or
a comparison where == was meant instead of =:

..\..\chrome\installer\mini_installer\mini_installer.cc(575,15) :
    error: using the result of an assignment as a condition without parentheses
        [-Werror,-Wparentheses]
    if (owner = reinterpret_cast<TOKEN_OWNER*>(::LocalAlloc(LPTR, size))) {
        ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Rather than just add parentheses, declare owner in this if, as it's not really
used outside the scope of the if.

BUG=82385
TBR=jschuh@chromium.org

Review URL: https://codereview.chromium.org/1523163005 .

Cr-Commit-Position: refs/heads/master@{#365519}