Revert of media: build fix about CdmAdapter (patchset #1 id:1 of https://codereview.chromium.org/1579493002/ )
Reason for revert:
This issue is known in crbug.com/506663 and we want to fix c++ spec and clang rather than making chromium code silly.
Nico asked to revert it.

Original issue's description:
> media: build fix about CdmAdapter
>
> clang complains it doesn't initialize const member, so this CL calls the
> default constructor explicitly.
>
> ../../media/cdm/cdm_adapter.cc:638:32: error: default initialization of an object of const type 'const Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
>   const Decryptor::AudioFrames empty_frames;
>                                ^
> 1 error generated
>
> Committed: https://crrev.com/6c4d42c0594cfcb6fffc00d22c52822d954a0566
> Cr-Commit-Position: refs/heads/master@{#368633}

TBR=dalecurtis@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1578263007

Cr-Commit-Position: refs/heads/master@{#369148}