Revert of ⛄ Capture Android stderr when symbolizing native stack traces. (patchset #1 id:1 of https://codereview.chromium.org/1886473002/ )
Reason for revert:
Seems to cause exception failures on the bots:
NameError: global name 'java_exceptions' is not defined

E.g.
https://uberchromegw.corp.google.com/i/chromium.android/builders/Android%20WebView%20CTS%20L-MR1%20%28dbg%29/builds/9749

What is |java_exceptions| at the end of stack_core.py?

Original issue's description:
> Capture Android stderr when symbolizing native stack traces.
>
> When native->Java results in a Java exception, upon the stack returning
> back to C++, we dump the Java exception to stderr and then signal a crash.
>
> Update our stack tool to capture Java-formatted stderr while processing logcat and dump
> all matching logs if the pid of the error matches the native stack.
> While this may sometimes be irrelevant, it can often include the Java
> exception and makes it easier to triage and less confusing.
>
> BUG=602651
>
> Committed: https://crrev.com/e35a5d8d7063a1feb552a3d517f600a071277285
> Cr-Commit-Position: refs/heads/master@{#386987}

TBR=rmcilroy@chromium.org,yfriedman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=602651

Review URL: https://codereview.chromium.org/1884873004

Cr-Commit-Position: refs/heads/master@{#387015}