Revert of Add options to write version number to registry. (patchset #14 id:260001 of https://codereview.chromium.org/1271893003/ )
Reason for revert:
This broke the Windows Clang build. The error is pointing out a real problem:

..\..\chrome\installer\setup\setup_main.cc(132,7) :
error: cannot pass object of non-trivial type 'base::string16'
(aka 'basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> >')
through variadic function; call will abort at runtime [-Wnon-pod-varargs]
      installer::GuidToSquid(product));
      ^

(From http://build.chromium.org/p/chromium.fyi/builders/CrWinClang/builds/3152/steps/compile/logs/stdio)

Original issue's description:
> Add options to write version number to registry.
>
> The MSI installer creates a DisplayVersion registry entry
> with an encoded version of Chrome's actual version.  Since
> this is done _after_ the setup call completes, we can't
> simply set the value in the normal setup process.  Instead,
> we launch a background process that waits a while (for
> msiexec to complete) and then writes the updated version.
>
> This is accomplished by having setup, upon successful completion,
> run itself in the background and then exit normally.
>
> --set-display-version-path="SOFTWARE\...\InstallProperties"
> --set-display-version-value="A.B.C.D"
> --delay=30
>
> BUG=67348
>
> Committed: https://crrev.com/0d3e644a25802bdb3afa7fc09eff5aab456c5733
> Cr-Commit-Position: refs/heads/master@{#348556}

TBR=robertshield@chromium.org,grt@chromium.org,bcwhite@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=67348

Review URL: https://codereview.chromium.org/1336923004

Cr-Commit-Position: refs/heads/master@{#348629}