Revert of Browser tests for the ChromeOS chromecast system tray item. (patchset #3 id:60001 of https://codereview.chromium.org/1287023010/ )
Reason for revert:
broke the compile on ChromeOS bots:

FAILED: ...
../../chrome/browser/ui/ash/system_tray_tray_cast_browsertest_chromeos.cc:53:10: error: variable 'result' is uninitialized when used here [-Werror,-Wuninitialized]
  return result;
         ^~~~~~
../../chrome/browser/ui/ash/system_tray_tray_cast_browsertest_chromeos.cc:51:14: note: initialize the variable 'result' to silence this warning
  bool result;
             ^
              = false

Original issue's description:
> Browser tests for the ChromeOS chromecast system tray item.
>
> This was initially reviewed in https://codereview.chromium.org/1231593002/. I've
> moved this to a new CL since there have been a few implementation changes and as
> a result this needs another look.
>
> BUG=497343,514952
>
> Committed: https://crrev.com/926097380c61018aa2d5dfc99299f592ccfa5738
> Cr-Commit-Position: refs/heads/master@{#344939}

TBR=achuith@chromium.org,oshima@chromium.org,jdufault@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=497343,514952

Review URL: https://codereview.chromium.org/1307863004

Cr-Commit-Position: refs/heads/master@{#344946}