Fix undefined GYP_MSVS_VERSION failure for non-googlers
This CL adds the missing GYP_MSVS_VERSION environment variable. Without
the patch the following error happen when a non-googler runs
gyp_chromium in Windows.

  File "E:\chromium\src\tools\gyp\pylib\gyp\MSVSVersion.py", line 430, in SelectVisualStudioVersion
    raise ValueError('GYP_MSVS_OVERRIDE_PATH requires GYP_MSVS_VERSION to be '
ValueError: GYP_MSVS_OVERRIDE_PATH requires GYP_MSVS_VERSION to be set to a particular version (e.g. 2010e).

The discussion is found here:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/XWZ3hZW8Lco

BUG=460462

Review URL: https://codereview.chromium.org/1593313002

Cr-Commit-Position: refs/heads/master@{#370065}