Revert of Release Oilpan heap singletons prior to LSan leak detection. (patchset #9 id:160001 of https://codereview.chromium.org/1491253004/ )
Reason for revert:
Might have caused compile failures on official Win builders:
https://chromegw.corp.google.com/i/official.desktop/builders/win/builds/268/steps/compile/logs/stdio
https://chromegw.corp.google.com/i/official.desktop/builders/win64/builds/264/steps/compile/logs/stdio

FAILED: ninja -t msvc -e environment.x64 -- "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\third_party\WebKit\Source\core\html\webcore_html_2.HTMLTableElement.obj.rsp /c ..\..\third_party\WebKit\Source\core\html\HTMLTableElement.cpp /Foobj\third_party\WebKit\Source\core\html\webcore_html_2.HTMLTableElement.obj /Fdobj\third_party\WebKit\Source\core\webcore_html_2.cc.pdb
c:\b\build\slave\win64\build\src\third_party\webkit\source\core\html\htmltableelement.cpp(413) : error C2039: 'registerAsStaticReference' : is not a member of 'blink::Persistent<blink::StylePropertySet>'
c:\b\build\slave\win64\build\src\third_party\webkit\source\core\html\htmltableelement.cpp(420) : error C2039: 'registerAsStaticReference' : is not a member of 'blink::Persistent<blink::StylePropertySet>'
c:\b\build\slave\win64\build\src\third_party\webkit\source\core\html\htmltableelement.cpp(423) : error C2039: 'registerAsStaticReference' : is not a member of 'blink::Persistent<blink::StylePropertySet>'
c:\b\build\slave\win64\build\src\third_party\webkit\source\core\html\htmltableelement.cpp(520) : error C2039: 'registerAsStaticReference' : is not a member of 'blink::Persistent<blink::StylePropertySet>'
c:\b\build\slave\win64\build\src\third_party\webkit\source\core\html\htmltableelement.cpp(523) : error C2039: 'registerAsStaticReference' : is not a member of 'blink::Persistent<blink::StylePropertySet>'
ninja: build stopped: subcommand failed.

Original issue's description:
> Release Oilpan heap singletons prior to LSan leak detection.
>
> Make Oilpan and LSan cooperate better. As Persistent<> references
> created via DEFINE_STATIC_LOCAL() and similar will be reachable to
> LSan's leak detection pass, the objects they refer to outside of
> the Oilpan heap will be reported as leaking.
>
> (This is in contrast to what happens in the non-Oilpan setting,
> where the (leaked) pointer created via DEFINE_STATIC_LOCAL() is
> stored in a local "static"; such non-global references are not
> considered roots to LSan and hence the objects reachable from
> those will not be reported as leaking.)
>
> Address the problem on the Oilpan side by having such "static"
> Persistent<>ly-held singletons be registered and tracked such
> that we're able to release them all just before shutting down
> and performing an extra round of GCs. Leaving a cleaner heap
> for LSan to work over. And to report no leaks over, ideally.
>
> As part of the changes needed to support this for Oilpan,
> wtf/LeakAnnotations.h offerings has been renamed and changed
> a bit:
>
>  * WTF_ANNOTATE_MEMORY_LEAK_SCOPE => LEAK_SANITIZER_DISABLED_SCOPE.
>    (but see LeakAnnotations.h for macro to use local to wtf/.)
>  * WTF_ANNOTATE_IGNORE_OBJECT_PTR => LEAK_SANITIZER_IGNORE_OBJECT.
>  * LEAK_SANITIZER_REGISTER_STATIC_LOCAL().
>
> R=haraken
> BUG=567257
>
> Committed: https://crrev.com/6918d00fae1ab739f89393378fa4adddabacafd2
> Cr-Commit-Position: refs/heads/master@{#363780}

TBR=oilpan-reviews@chromium.org,haraken@chromium.org,sigbjornf@opera.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=567257

Review URL: https://codereview.chromium.org/1502153005

Cr-Commit-Position: refs/heads/master@{#363812}